services:
  php-fpm:
    image: webdevops/php-nginx:8.1
    container_name: ${APP_NAME}_php
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    volumes:
      - '.:/app'
      - './docker/supervisor/laravel-worker.conf:/opt/docker/etc/supervisor.d/laravel-worker.conf'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment.rule=Host(`payment.maktabsharif.ir`)"
      - "traefik.http.routers.payment.entrypoints=web"
    networks:
      - web
      - mysql_server_mysql
      
  node:
    image: node:lts-alpine
    user: "node"
    working_dir: "/app"
    volumes:
      - '.:/app'
    command: sh -c "npm i && npm run prod"

networks:
  web:
    external: true
  mysql_server_mysql:
    external: true
